[package]
name = "framebuffer"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

[package.metadata.android]
label = "framebuffer"

[[bin]]
name = "framebuffer"
path = "src/main.rs"

[dependencies]
gl = "0.6.1"
glutin = "0.7.0"

[dependencies.gl_context]
path = "../.."
