[package]
name = "framebuffer"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

[package.metadata.android]
label = "framebuffer"

[[bin]]
name = "framebuffer"
path = "src/main.rs"


[dependencies]
gl = "*"
glutin = "*"

gl_context = {path = "../.."}
